project:
  type: website
  output-dir: docs

website:
  title: "Stephen Bond"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Projects.qmd
      - Recipe_Page.qmd
      - Resume.qmd

format:
  html:
    theme: styles.scss
    mainfont: EB Garamond
    css: styles.css
    toc: true
    page-layout: full



